spring:
  application:
    name: discovery-server
  config:
    location: optional:configserver:http://localhost:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false